name: 'Deploy on push'

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  forge-deploy:
    name: 'Laravel Forge Deploy'
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      # Trigger Laravel Forge Deploy
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          trigger_url: ${{ secrets.TRIGGER_URL }}
